In [6]:
class Student:
    def __init__(self, name, batch, roll):
        self.name = name
        self.batch = batch
        self.roll = roll
    def __str__(self):
        return f"Name: {self.name}\nBatch: {self.batch}\nRoll: {self.roll}"


In [1]:
class player:
    def __init__(self, name, club):
        self.name = name
        self.club = club
    def __str__(self):
        return f"Name: {self.name}\nClub: {self.club}"

In [2]:
messi = player("messi", "barca")

print(messi)

Name: messi
Club: barca


In [7]:
student = Student("Messi", 22, 10)
print(student)

Name: Messi
Batch: 22
Roll: 10


In [3]:
import numpy as np

In [9]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [10]:
type(array)

numpy.ndarray

In [13]:
array[0] = 83

In [14]:
array

array([83,  2,  3,  4,  5])

In [15]:
array[:2]

array([83,  2])

In [16]:
array = np.array([[1,2,3],[4,5,6]])

In [17]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

In [20]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [21]:
rand = np.empty(3)
rand

array([1., 1., 1.])

In [5]:
ones = np.ones((2,3))
ones[0][1] = 3
ones

array([[1., 3., 1.],
       [1., 1., 1.]])

In [28]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
np.random.random((3,4))

array([[0.11852816, 0.04190028, 0.08322575, 0.96756969],
       [0.90333456, 0.89151765, 0.64883829, 0.86941271],
       [0.63150331, 0.64086367, 0.79638617, 0.51620891]])

In [32]:
array = np.array([2,3,1])
array = np.sort(array)
array

array([1, 2, 3])

In [33]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [37]:
d = c.reshape(2,3)
d

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.transpose(d)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
d[d<6]

array([1, 2, 3, 4, 5])

In [42]:
np.arange(1,25).reshape(2,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [44]:
d = d[d<6]
d

array([1, 2, 3, 4, 5])

In [45]:
d*3

array([ 3,  6,  9, 12, 15])

In [46]:
d.min()

1

In [47]:
d.max()

5

In [48]:
d.sum()

15

In [6]:
array = np.arange(1,25).reshape(2,12)
array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [7]:
array.sum(axis=0)

array([14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36])

In [8]:
array.sum(axis=1)

array([ 78, 222])

In [52]:
array.max(axis=1)

array([12, 24])

In [53]:
array.max(axis=0)

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
array = array.max(axis=0)

unique_values, occurence_counts = np.unique(array, return_counts=True)

In [57]:
unique_values

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
occurence_counts

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [68]:
pred = np.array([8,3,8,3])
label = np.array([2,2,2,2])

mse = (1/len(pred)) * np.sum(np.square(pred-label))
mse

18.5

In [69]:
cross_entropy_loss = (-1/len(pred)) * np.sum(np.multiply(label, np.log(pred)))
cross_entropy_loss

-3.1780538303479458